### PR TITLE
css-canvas-medical - Alice Lee

### PR DESCRIPTION
**Pull request by alicejeeunlee**
https://user-images.githubusercontent.com/106103291/177065890-4f989794-a22d-43b6-a683-fa08c44d1545.mp4

### CODE REVIEW

**Review by codingcodymiller — APPROVED** [review]
**_Excellent_** work!! Let me know when your build of the implementation page is complete too, and I can review that for you as well 🏆

**Comment by alicejeeunlee** [comment]
https://user-images.githubusercontent.com/106103291/177386386-28858951-cc9d-475c-8af6-4f4df7c4abae.mp4

**Comment by alicejeeunlee** [comment]
https://user-images.githubusercontent.com/106103291/177418708-9f048f75-d9bc-468b-822e-43e39d689acd.mp4

**Comment by alicejeeunlee** [comment]
https://user-images.githubusercontent.com/106103291/177440292-5fde89bd-2e75-42c3-96a9-fa5be856c484.mp4

**Comment by alicejeeunlee** [comment]
https://user-images.githubusercontent.com/106103291/177490251-a65cf242-158c-49d6-9e25-521d747c9214.mp4

**Review by codingcodymiller — APPROVED** [review]
All of these pages look great!! Fantastic HTML and CSS 👏

**Comment by alicejeeunlee** [comment]
https://user-images.githubusercontent.com/106103291/177885720-bfd1050b-a41a-49a7-8cd5-69388d501d01.mp4

**Review by codingcodymiller — APPROVED** [review]

**Pull request merged**
